"""Exact finite visible instruments generated by a departure map."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping

from sympy import Matrix, zeros
from sympy.matrices import MatrixBase

from .rewrite import Refusal


@dataclass(frozen=True)
class VisibleInstrumentRequest:
    departure: MatrixBase
    effects: Mapping[str, MatrixBase]
    partition: tuple[str, ...]
    provenance: str
    resource_budget: int


@dataclass(frozen=True)
class MatrixResult:
    value: MatrixBase | None = None
    refusal: Refusal | None = None

    @property
    def accepted(self) -> bool:
        return self.refusal is None


@dataclass(frozen=True)
class VisibleInstrumentCompilation:
    instrument: "VisibleInstrument | None" = None
    refusal: Refusal | None = None

    @property
    def accepted(self) -> bool:
        return self.refusal is None


class VisibleInstrument:
    def __init__(
        self,
        departure: MatrixBase,
        effects: Mapping[str, MatrixBase],
        partition: tuple[str, ...],
        provenance: str,
        resource_cost: int,
    ):
        self.departure = departure
        self.effects = dict(effects)
        self.partition = partition
        self.provenance = provenance
        self.resource_cost = resource_cost
        self.inclusive = departure.H * departure
        self.effect_returns = {
            name: departure.H * effect * departure
            for name, effect in self.effects.items()
        }
        self.effect_certificates = {
            name: value.is_positive_semidefinite is True
            for name, value in self.effect_returns.items()
        }
        self.channel_cells = {
            name: self.effect_returns[name] for name in partition
        }
        if partition:
            channel_identity = Matrix.eye(departure.rows)
            partition_sum = sum(
                (self.effects[name] for name in partition),
                zeros(departure.rows),
            )
            self.partition_residual = partition_sum - channel_identity
        else:
            self.partition_residual = None
        self.cyclic_rank = _cyclic_rank(departure, tuple(self.effects.values()))

    def compress(self, observable: MatrixBase) -> MatrixResult:
        operator = Matrix(observable)
        if operator.shape != (self.departure.rows, self.departure.rows):
            return MatrixResult(refusal=Refusal(
                "observable shape does not match the channel fiber",
                residual=operator.shape,
                provenance=self.provenance,
            ))
        return MatrixResult(value=self.departure.H * operator * self.departure)

    def open_kernel(self, retained_resolvent: MatrixBase) -> MatrixResult:
        resolvent = Matrix(retained_resolvent)
        retained_dimension = self.departure.cols
        if resolvent.shape != (retained_dimension, retained_dimension):
            return MatrixResult(refusal=Refusal(
                "resolvent shape does not match the retained space",
                residual=resolvent.shape,
                provenance=self.provenance,
            ))
        return MatrixResult(
            value=self.departure * resolvent * self.departure.H,
        )


def _cyclic_rank(
    departure: MatrixBase,
    generators: tuple[MatrixBase, ...],
) -> int:
    basis = departure.columnspace()
    if not basis:
        return 0
    for _ in range(departure.rows):
        current = Matrix.hstack(*basis)
        candidates = [current]
        candidates.extend(generator * current for generator in generators)
        enlarged = Matrix.hstack(*candidates).columnspace()
        if len(enlarged) == len(basis):
            return len(basis)
        basis = enlarged
    return len(basis)


def _refusal(reason: str, request: VisibleInstrumentRequest, residual=()) -> VisibleInstrumentCompilation:
    return VisibleInstrumentCompilation(refusal=Refusal(
        reason,
        residual=residual,
        provenance=request.provenance,
    ))


def compile_visible_instrument(
    request: VisibleInstrumentRequest,
) -> VisibleInstrumentCompilation:
    try:
        departure = Matrix(request.departure)
    except (TypeError, ValueError):
        return _refusal("departure map is unavailable", request)
    if not departure.rows or not departure.cols:
        return _refusal("departure map is unavailable", request)

    channel_dimension = departure.rows
    effects: dict[str, MatrixBase] = {}
    for name, raw_effect in request.effects.items():
        effect = Matrix(raw_effect)
        if effect.shape != (channel_dimension, channel_dimension):
            return _refusal("effect shape does not match the channel fiber", request, effect.shape)
        if effect != effect.H:
            return _refusal("effect must be Hermitian", request, (name,))
        if effect.is_positive_semidefinite is not True:
            return _refusal("effect positivity is not certified", request, (name,))
        if (Matrix.eye(channel_dimension) - effect).is_positive_semidefinite is not True:
            return _refusal("effect upper bound is not certified", request, (name,))
        effects[name] = effect

    for name in request.partition:
        if name not in effects:
            return _refusal("partition effect is unavailable", request, (name,))
    if request.partition:
        partition_sum = sum(
            (effects[name] for name in request.partition),
            zeros(channel_dimension),
        )
        if partition_sum != Matrix.eye(channel_dimension):
            return _refusal(
                "detector partition must sum to the channel identity",
                request,
                tuple(partition_sum - Matrix.eye(channel_dimension)),
            )

    resource_cost = departure.rows * departure.cols + len(effects) * channel_dimension**2
    if request.resource_budget < resource_cost:
        return _refusal(
            "visible-instrument budget exceeded",
            request,
            (resource_cost, request.resource_budget),
        )
    return VisibleInstrumentCompilation(instrument=VisibleInstrument(
        departure,
        effects,
        request.partition,
        request.provenance,
        resource_cost,
    ))
