"""Trace-behavioral quotient of a native thermal right-action module."""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
import math

import numpy as np
from scipy.linalg import expm

from .impurity import AndersonSystem
from .native_car import (
    NativeOperator,
    NativeReachabilityModel,
    add_scaled_native,
    anderson_native_interaction,
    multiply_native,
    native_inner_product,
    native_local_operator,
    orthogonalize_native,
    trace_native,
)
from .native_dual import (
    anderson_native_free_hamiltonian,
    native_functional_seeds,
    native_projection_residual,
)
from .rewrite import Refusal


@dataclass(frozen=True)
class NativeThermalPacket:
    """Coupling coefficients; column zero is the partition function."""

    coefficients: np.ndarray


@dataclass(frozen=True)
class BehavioralObservability:
    """Orthonormal continuation rows generated by supplied reduced actions."""

    rows: np.ndarray
    closure_residual: float

    @property
    def rank(self) -> int:
        return self.rows.shape[0]


def behavioral_observability(
    actions: tuple[np.ndarray, ...],
    outputs: np.ndarray,
    tolerance: float,
) -> BehavioralObservability:
    """Close output covectors backward and expose their invariant row space."""
    if tolerance <= 0 or not math.isfinite(tolerance):
        raise ValueError("behavioral tolerance must be finite and positive")
    output_rows = np.atleast_2d(np.asarray(outputs, dtype=complex))
    width = output_rows.shape[1]
    normalized_actions = tuple(np.asarray(action, dtype=complex) for action in actions)
    if any(action.shape != (width, width) for action in normalized_actions):
        raise ValueError("behavioral action shape does not match output width")

    basis: list[np.ndarray] = []
    queue: deque[np.ndarray] = deque()

    def admit(candidate: np.ndarray):
        residual = candidate.copy()
        original_norm = float(np.linalg.norm(residual))
        if original_norm == 0:
            return
        for _ in range(2):
            for existing in basis:
                residual -= np.vdot(existing, residual) * existing
        norm = float(np.linalg.norm(residual))
        if norm <= tolerance * max(1.0, original_norm):
            return
        direction = residual / norm
        basis.append(direction)
        queue.append(direction)

    for row in output_rows:
        admit(row)
    while queue:
        row = queue.popleft()
        for action in normalized_actions:
            admit(row @ action)

    serialized = np.asarray(basis, dtype=complex).reshape(len(basis), width)
    residual = 0.0
    if basis:
        projector = serialized.conj().T @ serialized
        residual = max(
            float(np.max(np.linalg.norm(
                serialized @ action @ (np.eye(width) - projector),
                axis=1,
            )))
            for action in normalized_actions
        )
    return BehavioralObservability(serialized, residual)


@dataclass(frozen=True)
class NativeTraceHankelModel:
    prefix_ranks_by_grade: tuple[int, ...]
    prefix_support_by_grade: tuple[int, ...]
    behavioral_ranks_by_grade: tuple[int, ...]
    free_action: np.ndarray
    interaction_action: np.ndarray
    seed_coordinates: np.ndarray
    output_covectors_by_grade: tuple[np.ndarray, ...]
    total_prefix_rank: int
    total_behavioral_rank: int
    output_count: int
    retained_prefix_coefficients: int
    ambient_operator_dimension: int
    multiplication_terms: int
    normal_order_updates: int
    inner_product_work: int
    estimated_construction_operations: int
    closure_residual: float
    quotient_residual: float

    def thermal_packet(self, beta: float) -> NativeThermalPacket:
        if beta < 0 or not math.isfinite(beta):
            raise ValueError("thermal time must be finite and nonnegative")
        evolved = expm(-beta * (self.free_action + self.interaction_action))
        state = evolved @ self.seed_coordinates
        coefficients = np.asarray([
            covectors @ state for covectors in self.output_covectors_by_grade
        ])
        return NativeThermalPacket(coefficients)


@dataclass(frozen=True)
class NativeTraceHankelBoundary:
    active_phase: str
    prefix_ranks_by_grade: tuple[int, ...]
    prefix_support_by_grade: tuple[int, ...]
    retained_prefix_coefficients: int
    resource_used: int


@dataclass(frozen=True)
class NativeTraceHankelCompilation:
    model: NativeTraceHankelModel | None = None
    refusal: Refusal | None = None
    boundary: NativeTraceHankelBoundary | None = None

    @property
    def accepted(self) -> bool:
        return self.refusal is None


class _BudgetExceeded(Exception):
    pass


class _SupportExceeded(Exception):
    pass


def _refuse(system: AndersonSystem, reason: str, boundary=None):
    return NativeTraceHankelCompilation(
        refusal=Refusal(reason, provenance=system.request.provenance),
        boundary=boundary,
    )


def compile_native_trace_hankel(
    system: AndersonSystem,
    native: NativeReachabilityModel,
    thermal_order: int,
    tolerance: float,
    coefficient_budget: int,
    resource_budget: int,
):
    """Generate identity-reachable prefixes, then quotient by trace behavior."""
    if thermal_order < 0 or thermal_order > system.request.coefficient_order:
        return _refuse(system, "native trace-Hankel order lies outside the model")
    if tolerance <= 0 or not math.isfinite(tolerance):
        return _refuse(
            system, "native trace-Hankel tolerance must be finite and positive",
        )

    mode_count = 2 * len(system.request.bath_energies)
    identity = native_local_operator(np.eye(4, dtype=complex), (0, 0))
    free = anderson_native_free_hamiltonian(system)
    interaction = anderson_native_interaction(system)
    outputs, normal_updates, multiplication_terms = native_functional_seeds(
        native, system,
    )
    basis_by_grade: list[list[NativeOperator]] = [
        [] for _ in range(thermal_order + 1)
    ]
    work = inner_work = 0
    active_phase = "prefix grade 0"

    def boundary():
        support = tuple(
            sum(len(direction) for direction in basis)
            for basis in basis_by_grade
        )
        return NativeTraceHankelBoundary(
            active_phase=active_phase,
            prefix_ranks_by_grade=tuple(len(basis) for basis in basis_by_grade),
            prefix_support_by_grade=support,
            retained_prefix_coefficients=sum(support),
            resource_used=work,
        )

    def spend(amount: int):
        nonlocal work
        work += amount
        if work > resource_budget:
            raise _BudgetExceeded

    def admit(candidate: NativeOperator, grade: int):
        nonlocal inner_work
        result = orthogonalize_native(
            candidate,
            tuple(basis_by_grade[grade]),
            mode_count,
            tolerance,
        )
        inner_work += result.inner_product_work
        spend(result.estimated_work)
        if result.operator is None:
            return None
        basis_by_grade[grade].append(result.operator)
        retained = sum(
            len(direction)
            for basis in basis_by_grade
            for direction in basis
        )
        if retained > coefficient_budget:
            raise _SupportExceeded
        return result.operator

    def close_under_free(candidates, grade: int):
        nonlocal normal_updates, multiplication_terms
        queue = deque()
        for candidate in candidates:
            admitted = admit(candidate, grade)
            if admitted is not None:
                queue.append(admitted)
        while queue:
            image, updates, attempts = multiply_native(
                queue.popleft(), free, mode_count,
            )
            normal_updates += updates
            multiplication_terms += attempts
            spend(updates + attempts)
            admitted = admit(image, grade)
            if admitted is not None:
                queue.append(admitted)

    try:
        spend(
            normal_updates + multiplication_terms
            + len(identity) + len(free) + len(interaction)
        )
        close_under_free((identity,), 0)
        for grade in range(1, thermal_order + 1):
            active_phase = f"prefix grade {grade}"
            generated = []
            for direction in basis_by_grade[grade - 1]:
                image, updates, attempts = multiply_native(
                    direction, interaction, mode_count,
                )
                normal_updates += updates
                multiplication_terms += attempts
                spend(updates + attempts)
                generated.append(image)
            close_under_free(generated, grade)
    except _SupportExceeded:
        return _refuse(
            system, "native trace-Hankel support exceeded", boundary(),
        )
    except _BudgetExceeded:
        return _refuse(
            system, "native trace-Hankel resource budget exceeded", boundary(),
        )

    offsets = []
    total_rank = 0
    for basis in basis_by_grade:
        offsets.append(total_rank)
        total_rank += len(basis)
    full_free = np.zeros((total_rank, total_rank), dtype=complex)
    full_interaction = np.zeros_like(full_free)
    closure_residual = 0.0

    try:
        active_phase = "prefix actions"
        for grade, basis in enumerate(basis_by_grade):
            offset = offsets[grade]
            targets = (
                (full_free, free, basis, offset),
                *(() if grade == thermal_order else ((
                    full_interaction,
                    interaction,
                    basis_by_grade[grade + 1],
                    offsets[grade + 1],
                ),)),
            )
            for column, direction in enumerate(basis):
                for action, operator, target_basis, target_offset in targets:
                    image, updates, attempts = multiply_native(
                        direction, operator, mode_count,
                    )
                    normal_updates += updates
                    multiplication_terms += attempts
                    spend(updates + attempts)
                    reconstruction: NativeOperator = {}
                    for row, target in enumerate(target_basis):
                        coefficient, cost = native_inner_product(
                            target, image, mode_count,
                        )
                        inner_work += cost
                        spend(cost + len(target) + len(image))
                        action[target_offset + row, offset + column] = coefficient
                        add_scaled_native(reconstruction, target, coefficient)
                    residual = dict(image)
                    add_scaled_native(residual, reconstruction, -1.0)
                    residual_norm, cost = native_projection_residual(
                        residual, (), mode_count,
                    )
                    spend(cost)
                    closure_residual = max(closure_residual, residual_norm)

        active_phase = "trace outputs"
        full_outputs = np.zeros((len(outputs), total_rank), dtype=complex)
        for grade, basis in enumerate(basis_by_grade):
            offset = offsets[grade]
            for column, direction in enumerate(basis):
                for row, output in enumerate(outputs):
                    product, updates, attempts = multiply_native(
                        direction, output, mode_count,
                    )
                    normal_updates += updates
                    multiplication_terms += attempts
                    spend(updates + attempts)
                    full_outputs[row, offset + column] = trace_native(
                        product, mode_count,
                    )

        seed = np.zeros(total_rank, dtype=complex)
        for row, direction in enumerate(basis_by_grade[0]):
            coefficient, cost = native_inner_product(
                direction, identity, mode_count,
            )
            seed[row] = coefficient
            inner_work += cost
            spend(cost + len(direction) + len(identity))

        active_phase = "behavioral quotient"
        rows_by_grade: list[list[np.ndarray]] = [
            [] for _ in range(thermal_order + 1)
        ]
        row_queue: deque[tuple[int, np.ndarray]] = deque()

        def admit_row(candidate: np.ndarray, grade: int):
            grade_slice = slice(offsets[grade], offsets[grade] + len(basis_by_grade[grade]))
            local = candidate[grade_slice].copy()
            original_norm = float(np.linalg.norm(local))
            if original_norm == 0:
                return
            existing = rows_by_grade[grade]
            for _ in range(2):
                for row in existing:
                    local -= np.vdot(row[grade_slice], local) * row[grade_slice]
                    spend(2 * len(local))
            norm = float(np.linalg.norm(local))
            spend(len(local))
            if norm <= tolerance * max(1.0, original_norm):
                return
            admitted = np.zeros(total_rank, dtype=complex)
            admitted[grade_slice] = local / norm
            existing.append(admitted)
            row_queue.append((grade, admitted))

        for grade, basis in enumerate(basis_by_grade):
            grade_slice = slice(offsets[grade], offsets[grade] + len(basis))
            for output in full_outputs:
                candidate = np.zeros(total_rank, dtype=complex)
                candidate[grade_slice] = output[grade_slice]
                admit_row(candidate, grade)

        free_terms = int(np.count_nonzero(np.abs(full_free) > tolerance))
        interaction_terms = int(
            np.count_nonzero(np.abs(full_interaction) > tolerance)
        )
        while row_queue:
            grade, row = row_queue.popleft()
            spend(free_terms)
            admit_row(row @ full_free, grade)
            if grade > 0:
                spend(interaction_terms)
                admit_row(row @ full_interaction, grade - 1)
    except _SupportExceeded:
        return _refuse(
            system, "native trace-Hankel support exceeded", boundary(),
        )
    except _BudgetExceeded:
        return _refuse(
            system, "native trace-Hankel resource budget exceeded", boundary(),
        )

    flattened_rows = tuple(
        row for rows in rows_by_grade for row in rows
    )
    quotient = np.asarray(flattened_rows, dtype=complex)
    quotient_adjoint = quotient.conj().T
    quotient_free = quotient @ full_free @ quotient_adjoint
    quotient_interaction = quotient @ full_interaction @ quotient_adjoint
    quotient_seed = quotient @ seed
    compressed_outputs = []
    output_residual = 0.0
    for grade, basis in enumerate(basis_by_grade):
        grade_slice = slice(offsets[grade], offsets[grade] + len(basis))
        masked = np.zeros_like(full_outputs)
        masked[:, grade_slice] = full_outputs[:, grade_slice]
        compressed = masked @ quotient_adjoint
        compressed_outputs.append(compressed)
        output_residual = max(
            output_residual,
            float(np.linalg.norm(masked - compressed @ quotient)),
        )
    quotient_residual = max(
        output_residual,
        float(np.linalg.norm(
            quotient @ full_free - quotient_free @ quotient,
        )),
        float(np.linalg.norm(
            quotient @ full_interaction - quotient_interaction @ quotient,
        )),
    )

    if closure_residual > 20 * tolerance:
        return _refuse(system, "native trace-Hankel closure residual exceeded")
    if quotient_residual > 20 * tolerance:
        return _refuse(system, "native trace-Hankel quotient residual exceeded")

    support = tuple(
        sum(len(direction) for direction in basis)
        for basis in basis_by_grade
    )
    return NativeTraceHankelCompilation(model=NativeTraceHankelModel(
        prefix_ranks_by_grade=tuple(len(basis) for basis in basis_by_grade),
        prefix_support_by_grade=support,
        behavioral_ranks_by_grade=tuple(len(rows) for rows in rows_by_grade),
        free_action=quotient_free,
        interaction_action=quotient_interaction,
        seed_coordinates=quotient_seed,
        output_covectors_by_grade=tuple(compressed_outputs),
        total_prefix_rank=total_rank,
        total_behavioral_rank=len(flattened_rows),
        output_count=len(outputs),
        retained_prefix_coefficients=sum(support),
        ambient_operator_dimension=system.free_hamiltonian.size,
        multiplication_terms=multiplication_terms,
        normal_order_updates=normal_updates,
        inner_product_work=inner_work,
        estimated_construction_operations=work,
        closure_residual=closure_residual,
        quotient_residual=quotient_residual,
    ))
