"""Subtracted bubble boundaries and threshold diagnostics."""

from dataclasses import dataclass

from sympy import log, simplify, sympify

from .rewrite import Refusal


@dataclass(frozen=True)
class ShellDiagnostic:
    status: str
    gap: object
    nonlocal_coefficient: object
    isolated_pole_admissible: bool
    reason: str


@dataclass(frozen=True)
class BubbleBoundary:
    mass_squared: object
    subtraction_point: object
    provenance: str = "once-subtracted massive-massless bubble"

    @property
    def threshold(self):
        return self.mass_squared

    def primitive(self, spectral_parameter):
        """Finite bubble part normalized to vanish at zero."""
        spectral_parameter = sympify(spectral_parameter)
        if spectral_parameter.is_zero:
            return sympify(0)
        mu = self.mass_squared
        return simplify(
            1
            + (mu - spectral_parameter)
            / spectral_parameter
            * log(1 - spectral_parameter / mu)
        )

    def subtracted(self, spectral_parameter):
        return simplify(
            self.primitive(spectral_parameter)
            - self.primitive(self.subtraction_point)
        )

    def derivative(self, spectral_parameter):
        spectral_parameter = sympify(spectral_parameter)
        mu = self.mass_squared
        if spectral_parameter.is_zero:
            return simplify(1 / (2 * mu))
        return simplify(
            -1 / spectral_parameter
            - mu
            / spectral_parameter**2
            * log(1 - spectral_parameter / mu)
        )

    def density(self, energy):
        """Upper-boundary density on the declared domain energy >= threshold."""
        energy = sympify(energy)
        return simplify(1 - self.mass_squared / energy)

    def scalar_spin2_coefficient(self, spectral_parameter, dimension=4):
        spectral_parameter = sympify(spectral_parameter)
        dimension = sympify(dimension)
        if dimension == 2:
            raise ValueError("spin-two trace reversal is singular in dimension two")
        mu = self.mass_squared
        return simplify(
            4 * spectral_parameter * mu - 4 * mu**2 / (dimension - 2)
        )

    def scalar_spin2_density(self, energy, dimension=4):
        return simplify(
            self.scalar_spin2_coefficient(energy, dimension)
            * self.density(energy)
        )

    def diagnose_shell(self, shell_squared, dimension=4) -> ShellDiagnostic:
        shell_squared = sympify(shell_squared)
        gap = simplify(self.threshold - shell_squared)
        coefficient = self.scalar_spin2_coefficient(shell_squared, dimension)
        if gap == 0:
            return ShellDiagnostic(
                "threshold collision",
                gap,
                coefficient,
                False,
                "the continuum touches the shell and the bubble derivative diverges",
            )
        if gap.is_positive:
            return ShellDiagnostic(
                "below continuum",
                gap,
                coefficient,
                True,
                "the boundary is analytic here but does not solve the pole equation",
            )
        if gap.is_negative:
            return ShellDiagnostic(
                "inside continuum",
                gap,
                coefficient,
                False,
                "a real isolated pole is not admitted inside the open channel",
            )
        return ShellDiagnostic(
            "undecidable ordering",
            gap,
            coefficient,
            False,
            "the threshold relation needs stronger assumptions",
        )


@dataclass(frozen=True)
class BubbleCompilation:
    boundary: BubbleBoundary | None = None
    refusal: Refusal | None = None

    @property
    def accepted(self) -> bool:
        return self.refusal is None


@dataclass(frozen=True)
class ThresholdWindow:
    """Nested spectral effects generated by finite detector resolution."""

    boundary: BubbleBoundary
    resolution: object
    reference_resolution: object
    normalization: object
    dimension: object

    @property
    def interval(self):
        mu = self.boundary.threshold
        return mu, simplify(mu + self.resolution)

    def _cell_mass(self, resolution):
        mu = self.boundary.mass_squared
        d = self.dimension
        resolution = sympify(resolution)
        return simplify(
            4
            * mu
            * (
                resolution**2 / 2
                - mu * resolution / (d - 2)
                + mu**2 / (d - 2) * log(1 + resolution / mu)
            )
        )

    @property
    def unnormalized_response(self):
        return self._cell_mass(self.resolution)

    @property
    def unnormalized_reference_response(self):
        return self._cell_mass(self.reference_resolution)

    @property
    def response(self):
        return simplify(self.normalization * self.unnormalized_response)

    @property
    def external_ideal_witness(self):
        """Detector value on the shell-displacement ideal generator."""
        mu = self.boundary.mass_squared
        d = self.dimension
        delta = self.resolution
        moment = 4 * mu * (
            delta**3 / 3
            - mu
            / (d - 2)
            * (
                delta**2 / 2
                - mu * delta
                + mu**2 * log(1 + delta / mu)
            )
        )
        return simplify(self.normalization * moment)

    @property
    def conditional_fraction(self):
        return simplify(
            self.unnormalized_response
            / self.unnormalized_reference_response
        )


@dataclass(frozen=True)
class ThresholdWindowCompilation:
    window: ThresholdWindow | None = None
    refusal: Refusal | None = None

    @property
    def accepted(self) -> bool:
        return self.refusal is None


def compile_subtracted_bubble(
    mass_squared, subtraction_point=0
) -> BubbleCompilation:
    mass_squared = sympify(mass_squared)
    subtraction_point = sympify(subtraction_point)
    if mass_squared.is_positive is not True:
        return BubbleCompilation(
            refusal=Refusal(
                "bubble threshold requires positive mass squared",
                provenance="massive-massless bubble",
            )
        )
    if simplify(mass_squared - subtraction_point).is_positive is not True:
        return BubbleCompilation(
            refusal=Refusal(
                "subtraction point must lie below the bubble threshold",
                provenance="massive-massless bubble",
            )
        )
    return BubbleCompilation(
        boundary=BubbleBoundary(mass_squared, subtraction_point)
    )


def compile_threshold_window(
    boundary,
    resolution,
    reference_resolution,
    normalization=1,
    dimension=4,
) -> ThresholdWindowCompilation:
    """Compile one detector cell and its normalization-free nested fraction."""
    resolution = sympify(resolution)
    reference_resolution = sympify(reference_resolution)
    normalization = sympify(normalization)
    dimension = sympify(dimension)

    if resolution.is_positive is not True:
        return ThresholdWindowCompilation(
            refusal=Refusal(
                "resolution must be positive",
                provenance="threshold spectral detector",
            )
        )
    if simplify(reference_resolution - resolution).is_nonnegative is not True:
        return ThresholdWindowCompilation(
            refusal=Refusal(
                "reference resolution must contain the detector window",
                provenance="threshold spectral detector",
            )
        )
    if normalization.is_positive is not True:
        return ThresholdWindowCompilation(
            refusal=Refusal(
                "spectral normalization must be positive",
                provenance="threshold spectral detector",
            )
        )
    if simplify(dimension - 3).is_nonnegative is not True:
        return ThresholdWindowCompilation(
            refusal=Refusal(
                "positive spin-two window requires dimension at least three",
                provenance="threshold spectral detector",
            )
        )
    return ThresholdWindowCompilation(
        window=ThresholdWindow(
            boundary,
            resolution,
            reference_resolution,
            normalization,
            dimension,
        )
    )
