"""Exact two-sector coefficient algebra generated by a Hermitian involution."""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction

import exact_gaussian_matrix as gaussian


class CoefficientAlgebraError(ValueError):
    def __init__(self, kind: str, reason: str):
        super().__init__(reason)
        self.kind = kind


@dataclass(frozen=True)
class CoefficientAlgebra:
    grading: gaussian.ComplexMatrix
    coefficient: gaussian.ComplexMatrix
    projectors: tuple[gaussian.ComplexMatrix, gaussian.ComplexMatrix]
    eigenvalues: tuple[Fraction, Fraction]
    coordinates: tuple[Fraction, Fraction]
    minimal_polynomial: tuple[Fraction, ...]
    coefficient_projectors: tuple[gaussian.ComplexMatrix, gaussian.ComplexMatrix] | None
    checks: dict[str, bool]


def _trace(value: gaussian.ComplexMatrix) -> gaussian.Gaussian:
    return sum((value[index][index] for index in range(len(value))), gaussian.ZERO)


def _sector_scalar(
    coefficient: gaussian.ComplexMatrix, projector: gaussian.ComplexMatrix
) -> Fraction:
    projector_trace = _trace(projector)
    if projector_trace.imaginary or projector_trace.real == 0:
        raise CoefficientAlgebraError(
            "DegenerateGradingSector", "each grading projector must have positive exact trace"
        )
    restricted_trace = _trace(gaussian.multiply(projector, coefficient))
    if restricted_trace.imaginary:
        raise CoefficientAlgebraError(
            "NonRealSectorCoefficient", "sector coefficient trace must be real"
        )
    value = restricted_trace.real / projector_trace.real
    if gaussian.multiply(coefficient, projector) != gaussian.scale(projector, value):
        raise CoefficientAlgebraError(
            "NonScalarGradingSector",
            "the coefficient is not scalar on a curvature-grading sector",
        )
    return value


def _polynomial(
    coefficients: tuple[Fraction, ...], value: gaussian.ComplexMatrix
) -> gaussian.ComplexMatrix:
    result = gaussian.zero(len(value))
    power = gaussian.identity(len(value))
    for coefficient in coefficients:
        result = gaussian.add(result, gaussian.scale(power, coefficient))
        power = gaussian.multiply(power, value)
    return result


def construct(
    grading: gaussian.ComplexMatrix, coefficient: gaussian.ComplexMatrix
) -> CoefficientAlgebra:
    if len(grading) != len(coefficient):
        raise CoefficientAlgebraError(
            "CoefficientDimensionMismatch", "grading and coefficient dimensions differ"
        )
    unit = gaussian.identity(len(grading))
    if not gaussian.is_hermitian(grading) or gaussian.multiply(grading, grading) != unit:
        raise CoefficientAlgebraError(
            "InvalidCoefficientGrading", "the coefficient grading must be a Hermitian involution"
        )
    if not gaussian.is_hermitian(coefficient):
        raise CoefficientAlgebraError(
            "NonHermitianCoefficient", "the longitudinal coefficient must be Hermitian"
        )
    if gaussian.bracket(grading, coefficient) != gaussian.zero(len(grading)):
        raise CoefficientAlgebraError(
            "NoncommutingCoefficientAlgebra",
            "the longitudinal coefficient does not commute with the curvature grading",
        )

    plus = gaussian.scale(gaussian.add(unit, grading), Fraction(1, 2))
    minus = gaussian.scale(
        gaussian.add(unit, gaussian.scale(grading, Fraction(-1))), Fraction(1, 2)
    )
    aligned = _sector_scalar(coefficient, plus)
    antialigned = _sector_scalar(coefficient, minus)
    identity_coordinate = (aligned + antialigned) / 2
    grading_coordinate = (aligned - antialigned) / 2
    reconstructed = gaussian.add(
        gaussian.scale(unit, identity_coordinate),
        gaussian.scale(grading, grading_coordinate),
    )

    coefficient_projectors = None
    if aligned == antialigned:
        minimal_polynomial = (-aligned, Fraction(1))
    else:
        minimal_polynomial = (
            aligned * antialigned,
            -(aligned + antialigned),
            Fraction(1),
        )
        difference = aligned - antialigned
        derived_plus = gaussian.scale(
            gaussian.add(coefficient, gaussian.scale(unit, -antialigned)),
            Fraction(1, 1) / difference,
        )
        derived_minus = gaussian.add(unit, gaussian.scale(derived_plus, Fraction(-1)))
        coefficient_projectors = (derived_plus, derived_minus)

    checks = {
        "grading_involutive": gaussian.multiply(grading, grading) == unit,
        "coefficient_commutes_with_grading": gaussian.bracket(grading, coefficient)
        == gaussian.zero(len(grading)),
        "coefficient_reconstructed": reconstructed == coefficient,
        "minimal_polynomial_annihilates_coefficient": _polynomial(minimal_polynomial, coefficient)
        == gaussian.zero(len(coefficient)),
        "coefficient_projectors_match_grading": coefficient_projectors is None
        or coefficient_projectors == (plus, minus),
    }
    if not all(checks.values()):
        failed = next(name for name, passed in checks.items() if not passed)
        raise CoefficientAlgebraError(
            "CoefficientAlgebraResidual", f"coefficient algebra construction fails at {failed}"
        )
    return CoefficientAlgebra(
        grading,
        coefficient,
        (plus, minus),
        (aligned, antialigned),
        (identity_coordinate, grading_coordinate),
        minimal_polynomial,
        coefficient_projectors,
        checks,
    )


def witness(value: CoefficientAlgebra) -> dict[str, object]:
    aligned, antialigned = value.eigenvalues
    identity_coordinate, grading_coordinate = value.coordinates
    return {
        "kind": "exact-involutive-two-sector-star-algebra",
        "dimension": 2,
        "basis": ["I", "Sigma_F"],
        "relations": {"Sigma_F^2": "I", "star_fixed_basis": True},
        "coefficient_coordinates": {
            "identity": gaussian.rational_text(identity_coordinate),
            "grading": gaussian.rational_text(grading_coordinate),
        },
        "sector_eigenvalues": {
            "curvature_aligned": gaussian.rational_text(aligned),
            "curvature_antialigned": gaussian.rational_text(antialigned),
        },
        "minimal_polynomial": [
            gaussian.rational_text(coefficient) for coefficient in value.minimal_polynomial
        ],
        "projectors_from_coefficient": (
            None
            if value.coefficient_projectors is None
            else {
                "curvature_aligned": gaussian.serialize(value.coefficient_projectors[0]),
                "curvature_antialigned": gaussian.serialize(value.coefficient_projectors[1]),
            }
        ),
        "checks": value.checks,
    }
