"""Structural even-parity Galerkin adapter for the quartic oscillator.

The basis is ``H_(2j)(x) exp(-x^2/2)`` with the common ``sqrt(pi)`` removed from
its Gram metric.  Multiplication by ``x`` is generated by the Hermite recurrence,
not by quadrature or a table of quartic matrix entries.
"""

from __future__ import annotations

import argparse
import math
import sys
from collections.abc import Sequence
from fractions import Fraction

from cyclic_reduce import AdmissibilityError, Matrix, reduce_symmetric_matrix


def _exact(value: Fraction | int | str) -> Fraction:
    if isinstance(value, (bool, float)):
        raise AdmissibilityError("coupling must be an exact rational")
    try:
        return value if isinstance(value, Fraction) else Fraction(value)
    except (TypeError, ValueError, ZeroDivisionError) as error:
        raise AdmissibilityError("coupling must be an exact rational") from error


def _multiply_by_x(coefficients: dict[int, Fraction]) -> dict[int, Fraction]:
    """Apply x H_n = H_(n+1)/2 + n H_(n-1)."""

    result: dict[int, Fraction] = {}
    for degree, coefficient in coefficients.items():
        result[degree + 1] = result.get(degree + 1, Fraction(0)) + coefficient / 2
        if degree:
            result[degree - 1] = result.get(degree - 1, Fraction(0)) + degree * coefficient
    return result


def build_even_quartic_galerkin(
    levels: int,
    coupling: Fraction | int | str,
) -> tuple[Matrix, Matrix]:
    """Return ``P_even(-d^2+x^2+g x^4)P_even`` and its exact Gram metric."""

    if isinstance(levels, bool) or not isinstance(levels, int) or levels <= 0:
        raise AdmissibilityError("levels must be a positive integer")
    strength = _exact(coupling)
    operator = [[Fraction(0) for _ in range(levels)] for _ in range(levels)]
    metric = [[Fraction(0) for _ in range(levels)] for _ in range(levels)]

    for column in range(levels):
        degree = 2 * column
        operator[column][column] += 2 * degree + 1
        coefficients = {degree: Fraction(1)}
        for _ in range(4):
            coefficients = _multiply_by_x(coefficients)
        for target_degree, coefficient in coefficients.items():
            if target_degree % 2 == 0 and target_degree < 2 * levels:
                operator[target_degree // 2][column] += strength * coefficient
        metric[column][column] = Fraction(2**degree * math.factorial(degree))

    return tuple(tuple(row) for row in operator), tuple(tuple(row) for row in metric)


def _main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Probe an exact even Hermite-Galerkin quartic carrier."
    )
    parser.add_argument("--levels", type=int, required=True)
    parser.add_argument("--coupling", required=True, help="exact rational g")
    parser.add_argument("--budget", type=int)
    parser.add_argument("--time-horizon")
    parser.add_argument("--tolerance")
    arguments = parser.parse_args(argv)
    try:
        matrix, metric = build_even_quartic_galerkin(
            arguments.levels,
            arguments.coupling,
        )
        preparation = [1] + [0] * (arguments.levels - 1)
        result = reduce_symmetric_matrix(
            matrix,
            preparation,
            metric=metric,
            budget=arguments.budget,
            time_horizon=arguments.time_horizon,
            tolerance=arguments.tolerance,
        )
    except AdmissibilityError as error:
        print(f"Refused: {error}")
        return 2
    print(
        "finite Galerkin probe only: no continuum-PDE convergence certificate\n" + result.summary()
    )
    return 0


if __name__ == "__main__":
    sys.exit(_main())
